### ISSUE TITLE
Flowsynth should have packaging and be published to pypi.org

### ISSUE THREAD

**Issue by bac** [secureworks/flowsynth#15]
Would be very helpful if flowsynth could be installed via `pip`. Even better if it were in `pypi.org`.

PR here: https://github.com/secureworks/flowsynth/pull/14

**Comment by q2dg** [comment]
Well...sadly it seems this project is a bit stalled...

**Comment by counterthreatunit** [comment]
Done.  https://pypi.org/project/flowsynth/

Still room for improvement though -- https://github.com/secureworks/flowsynth/blob/950b8d0d23adde43e98332407766efa1523908c5/src/flowsynth.py#L758-L760
