### ISSUE TITLE
Trivial: python2 prints not entirely correct.

### ISSUE THREAD

**Issue by bac** [secureworks/flowsynth#23]
Flowsynth strives to be py2 and py3 compatible.  The `print "foo"` statements from py2 have been converted to _look like_ python3 print functions but they aren't.  The difference is explained at: https://stackoverflow.com/questions/12162629/using-print-the-function-version-in-python2-x

Simple fix is to include `from __future__ import print_function` at the top of the modules.

**Comment by counterthreatunit** [comment]
Are you seeing any of the existing print statements adversely affected by this?

> $ grep -n print flowsynth.py | grep -vP "^\d+\x3A\s*(#|\x22)"
874:            print("\n ~~ Build Summary ~~")
875:            print("Runtime:\t\t%ss\nOutput format:\t\t%s\nRaw instructions:\t%s\nTimeline events:\t%s\nPackets generated:\t%s\n" % ( RUNTIME, ARGS.output_format, len(COMPILER_INSTRUCTIONS), len(COMPILER_TIMELINE), len(COMPILER_OUTPUT)))
877:            print(json.dumps(BUILD_STATUS))
1102:    print(json.dumps(BUILD_STATUS))

**Comment by bac** [comment]
To answer your question, no, none of the code is currently _broken_, meaning it does something close to right, but not for the reason you may think.

In python2 `print` is a statement, not a function. Your call ` print("\n ~~ Build Summary ~~")` is semantically different in python2 vs python3.  In py2 you are calling the print statement with a single string. The parens aren't there to make it a function call, they are wrapping the string.  So if you have one item inside the parens the result is a string, and the output will be the same in py2 and py3.

If, however, you have `print("hello", "world")` the argument passed the print statement is now a tuple, not a string.  And you'll get different results in 2 vs 3.  So your current code base is "lucky" in that all of the print statements are decorated to look like you are calling a function and you just happen to have a single argument, instead of the `n` arguments you could use.

 If someone adds `print "hello world"` and only tests in python2 it will work there and break in python3.

If you make the accepted and suggested change, you will be protected.  `print()` will be a function in both environments and do what is expected.  And if someone adds `print "hello world"` it will break in both environments.

The suggested change supports defensive programming and is good practice.
